startweet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('timeline/', include('timeline.urls')),
    path('admin/', admin.site.urls),
]

timeline/urls.py
from django.urls import path

from . import views, tweepy_func

app_name = 'timeline'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('user/<int:id>/', views.UserView.as_view(), name='user'),
    path('list/<int:id>/', views.ListView.as_view(), name='list'),
    path('login/', tweepy_func.login, name='login'),
    path('oauth/', tweepy_func.oauth, name='oauth'),
    path('like_home/', tweepy_func.like_home, name='like_home'),
]

timeline/models.py
from django.db import models

# Create your models here.

timeline/views.py
from . import tweepy_func

from django.shortcuts import redirect
from django.views.generic import TemplateView


class TimelineViewBase(TemplateView):
    template_name = 'timeline/index.html'

    def get(self, request, *args, **kwargs):
        if not ('access_token' and 'access_token_secret') in request.session:
            return redirect('timeline:login')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        client = tweepy_func.create_client(self.request.session['access_token'], self.request.session['access_token_secret'])
        if 'search_username' in request.POST:
            search_username = request.POST['search_username']
            id = client.get_user(username=str(search_username)).json()['data']['id']
            return redirect('timeline:user', id)
        elif 'like_username' in request.POST:
            like_username = request.POST['like_username']
            id = client.get_user(username=str(like_username)).json()['data']['id']
            tweepy_func.like_user_tweets(client, id, 20)
            return redirect('timeline:user', id)
        elif 'rt_username' in request.POST:
            rt_username = request.POST['rt_username']
            id = client.get_user(username=str(rt_username)).json()['data']['id']
            tweepy_func.rt_user_tweets(client, id, 10)
            return redirect('timeline:user', id)
        elif 'like_home_limit' in request.POST:
            tweepy_func.like_home(client, request.POST['like_home_limit'])
            return redirect('timeline:index')


class IndexView(TimelineViewBase):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        client = tweepy_func.create_client(self.request.session['access_token'], self.request.session['access_token_secret'])
        context['lists'] = tweepy_func.get_pinned_lists(client)
        context['me'] = client.get_me().json()['data']['id']

        tweets = tweepy_func.page_home(client, days=3)
        context['tweets'] = sorted(tweets, key=lambda x: -(x['public_metrics']['retweet_count'] * 2 + x['public_metrics']['like_count']))

        return context


class UserView(TimelineViewBase):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        client = tweepy_func.create_client(self.request.session['access_token'], self.request.session['access_token_secret'])
        context['lists'] = tweepy_func.get_pinned_lists(client)
        context['me'] = client.get_me().json()['data']['id']

        id = self.kwargs.get('id', '')
        tweets = tweepy_func.page_user(client, id, days=7)
        context['tweets'] = sorted(tweets, key=lambda x: -(x['public_metrics']['retweet_count'] * 2 + x['public_metrics']['like_count']))

        return context


class ListView(TimelineViewBase):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        client = tweepy_func.create_client(self.request.session['access_token'], self.request.session['access_token_secret'])
        context['lists'] = tweepy_func.get_pinned_lists(client)
        context['me'] = client.get_me().json()['data']['id']

        id = self.kwargs.get('id', '')
        tweets = tweepy_func.page_list(client, id, days=7)
        context['tweets'] = sorted(tweets, key=lambda x: -(x['public_metrics']['retweet_count'] * 2 + x['public_metrics']['like_count']))

        return context

timeline/templates/timeline/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>StarTweet</title>
    <meta name="description" content="StarTweet Twitter application that pursues simplicity and efficiency">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'timeline/images/logo.png' %}">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!-- mine -->
    <link rel="stylesheet" href="{% static 'timeline/style.css' %}">
    <script src="{% static 'timeline/script.js' %}"></script>
</head>

<body>
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col col-lg-7">
                <div class="card m-2"><a class="btn btn-primary" href="{% url 'timeline:index' %}" role="button">timeline</a></div>
                {% for list in lists %}
                <div class="card m-2"><a class="btn btn-primary" href="{% url 'timeline:list' list.id %}" role="button">{{ list.name }}</a></div>
                {% endfor %}
                <div class="card m-2"><a class="btn btn-primary" href="{% url 'timeline:user' me %}" role="button">me</a></div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row m-2 g-2 align-items-center">
                        <div class="col-3">
                            <label class="form-label">search user tweets</label>
                        </div>
                        <div class="col-auto">
                            <input class="form-control" type="text" placeholder="mi0256" name="search_username">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-primary">Search</button>
                        </div>
                    </div>
                </form>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row m-2 g-2 align-items-center">
                        <div class="col-3">
                            <label class="form-label">like user tweets</label>
                        </div>
                        <div class="col-auto">
                            <input class="form-control" type="text" placeholder="mi0256" name="like_username">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-warning">Like</button>
                        </div>
                    </div>
                </form>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row m-2 g-2 align-items-center">
                        <div class="col-3">
                            <label class="form-label">rt user tweets</label>
                        </div>
                        <div class="col-auto">
                            <input class="form-control" type="text" placeholder="mi0256" name="rt_username">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-success">RT</button>
                        </div>
                    </div>
                </form>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row m-2 g-2 align-items-center">
                        <div class="col-3">
                            <label class="form-label">like home</label>
                        </div>
                        <div class="col-auto">
                            <input class="form-control" type="text" placeholder="20" name="like_home_limit">
                        </div>
                        <div class="col-auto">
                            <button type="submit" class="btn btn-outline-danger">Like</button>
                        </div>
                    </div>
                </form>
                {% for tweet in tweets %}
                <div class="card m-2">
                    <div class="card-body" style="background-color: rgb(250, 250, 255);">
                        <img src={{ tweet.profile_image_url }}><br>
                        <a href="{% url 'timeline:user' tweet.author_id %}" class="card-link">{{ tweet.name }} - {{ tweet.created_at }}</a>
                        <p>{{ tweet.text | linebreaksbr }}</p>
                        <p style="text-align: right;">
                            ✨:{{ tweet.public_metrics.virtual_engagement }}% 
                            👀:{{ tweet.public_metrics.impression_count }} 
                            🔁:{{ tweet.public_metrics.retweet_count }} 
                            ❤️:{{ tweet.public_metrics.like_count }}
                        </p>
                        <a class="btn btn-primary" href="https://twitter.com/user/status/{{ tweet.id }}" target="_blank" rel="noopener noreferrer">view</a>
                        {% for media_url in tweet.media_url %}
                            <div class="tweet_media"><img src={{ media_url }}></div>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>

</html>